CREATE TABLE Users(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Name VARCHAR(40) NOT NULL,
    LName VARCHAR(40) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Pw VARCHAR(50) NOT NULL,
    Rank TINYINT NOT NULL
);

CREATE TABLE Mails(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Asunto VARCHAR(100) NOT NULL, 
    Email VARCHAR(40) NOT NULL,
    Phone VARCHAR(40) NOT NULL,
    Content TEXT,
    Date DATETIME NOT NULL
 );

 CREATE TABLE Files(
        ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
        Type VARCHAR(40) NOT NULL,
        MailID INT ,
        FOREIGN KEY(MailID)  REFERENCES Mails(ID)
 );